alertmanager:
  enabled: true
  persistentVolume:
    enabled: false
  replicaCount: 1
  resources:
    limits:
      memory: 100Mi
      cpu: 100m

grafana:
  enabled: true
  adminPassword: "admin"
  persistence:
    enabled: false
  resources:
    requests:
      memory: 300Mi
      cpu: 100m
    limits:
      memory: 600Mi
      cpu: 200m
  service:
    type: ClusterIP
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      isDefault: false
      editable: false

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false

nodeExporter:
  enabled: true

prometheus-node-exporter:
  enabled: true
  hostNetwork: true
  service:
    port: 19100
    targetPort: 19100
    name: metrics
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 100Mi
      cpu: 100m

prometheus:
  enabled: true
  prometheusSpec:
    retention: 24h
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      any: true
    podMonitorSelectorNilUsesHelmValues: false
    replicas: 1
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    resources:
      limits:
        memory: 300Mi
        cpu: 200m

kube-state-metrics:
  enabled: true
  resources:
    limits:
      memory: 100Mi
      cpu: 100m
